"""Provider-neutral LLM contracts and offline test provider."""

from financial_research_agent.llm.contracts import (
    ChatMessage,
    ChatProvider,
    ChatRequest,
    ChatResponse,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingResponse,
    FinishReason,
    MessageRole,
    ModelMetadata,
    ProviderCapability,
    ProviderError,
    ProviderErrorCode,
    ResponseFormat,
    ResponseFormatType,
    RetryPolicy,
    StreamEvent,
    StreamEventType,
    TokenUsage,
    ToolCall,
    ToolDefinition,
)
from financial_research_agent.llm.local_openai import (
    LocalEndpointHealth,
    LocalRuntime,
    OpenAICompatibleLocalProvider,
)
from financial_research_agent.llm.offline import OfflineTestProvider
from financial_research_agent.llm.openai import (
    OnlineProviderHealth,
    OpenAIModelProfile,
    OpenAIProvider,
    openai_model_profile,
)
from financial_research_agent.llm.registry import (
    ProviderRegistry,
    create_default_provider_registry,
    create_offline_provider_registry,
)

__all__ = [
    "ChatMessage",
    "ChatProvider",
    "ChatRequest",
    "ChatResponse",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "FinishReason",
    "LocalEndpointHealth",
    "LocalRuntime",
    "MessageRole",
    "ModelMetadata",
    "OfflineTestProvider",
    "OnlineProviderHealth",
    "OpenAICompatibleLocalProvider",
    "OpenAIModelProfile",
    "OpenAIProvider",
    "ProviderCapability",
    "ProviderError",
    "ProviderErrorCode",
    "ProviderRegistry",
    "ResponseFormat",
    "ResponseFormatType",
    "RetryPolicy",
    "StreamEvent",
    "StreamEventType",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "create_default_provider_registry",
    "create_offline_provider_registry",
    "openai_model_profile",
]
